// Mock schedule for one day. Shape matches the schedule model
// described in the project spec (id, title, start/end, status...).
// Later this will come from aiService / the Django backend instead.

export const mockSchedule = [
  {
    id: 'task-001',
    title: 'DSA',
    description: 'Solve 3 Binary Tree Problems',
    startTime: '07:00',
    endTime: '09:00',
    durationMinutes: 120,
    type: 'study',
    status: 'completed',
    priority: 'high',
    fixed: false,
  },
  {
    id: 'task-002',
    title: 'College',
    description: 'Regular classes',
    startTime: '09:00',
    endTime: '16:00',
    durationMinutes: 420,
    type: 'college',
    status: 'completed',
    priority: 'high',
    fixed: true,
  },
  {
    id: 'task-003',
    title: 'ML Project',
    description: 'Work on the timetable scheduling engine',
    startTime: '16:00',
    endTime: '19:00',
    durationMinutes: 180,
    type: 'project',
    status: 'current',
    priority: 'high',
    fixed: false,
  },
  {
    id: 'task-004',
    title: 'Assignment',
    description: 'Finish pending DBMS assignment',
    startTime: '19:00',
    endTime: '20:00',
    durationMinutes: 60,
    type: 'assignment',
    status: 'upcoming',
    priority: 'medium',
    fixed: false,
  },
  {
    id: 'task-005',
    title: 'Exercise',
    description: '45 minute workout',
    startTime: '20:00',
    endTime: '20:45',
    durationMinutes: 45,
    type: 'exercise',
    status: 'upcoming',
    priority: 'low',
    fixed: false,
  },
  {
    id: 'task-006',
    title: 'Sleep',
    description: 'Wind down and sleep',
    startTime: '23:30',
    endTime: '06:30',
    durationMinutes: 420,
    type: 'sleep',
    status: 'upcoming',
    priority: 'high',
    fixed: true,
  },
]
